# Generated by Django 3.1.3 on 2020-11-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='owner',
        ),
    ]
