# Generated by Django 3.1.3 on 2020-11-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201113_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
