# Generated by Django 3.1.3 on 2020-11-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_client_ready'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=512)),
                ('option1', models.CharField(blank=True, max_length=256, null=True)),
                ('option2', models.CharField(blank=True, max_length=256, null=True)),
                ('option3', models.CharField(blank=True, max_length=256, null=True)),
                ('answer', models.IntegerField(default=0)),
                ('kind', models.CharField(choices=[('Question Cam', 'question_cam'), ('Question Options', 'question_options')], max_length=64)),
            ],
        ),
    ]
